# -*- coding: utf-8 -*-
"""Quote Guessing Game using Web Scraping in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dc2tDnyEdcTOn3hcOiMt4cfzJepZxVn2
"""

import requests
from bs4 import BeautifulSoup
from time import sleep
from random import choice

base_url = "http://quotes.toscrape.com/"
# url to navigate pages
url = "/page/1"
# list for all quotes
all_quotes = []

while url:
  res = requests.get(f"{base_url}{url}")
  print(f"Now scarping {base_url}{url}")
  soup = BeautifulSoup(res.text, "html.parser")

  quotes = soup.find_all(class_="quote")

  for quote in quotes:
    all_quotes.append({
        "text": quote.find(class_="text").get_text(),
        "author": quote.find(class_="author").get_text(),
        "bio-link": quote.find("a")["href"]
    })
    next_btn = soup.find(classs_="next")
    url = next_btn.find("a")["href"] if next_btn else None
    sleep(2)

quote = choice(all_quotes)
remaining_guesses = 4
print("Here's the quote: ")
print(quote['text'])

guess = ""
while guess.lower() != quote['author'].lower and remaining_guesses > 0:
  guess = input(f"Who's the author? Remaining guesses : {remaining_guesses} ")

  if guess == quote['author']:
    print("Congratulations you guessed it right!!!")
    break
  remaining_guesses -= 1

  if remaining_guesses == 3:
    res = requests.get(f"{base_url}{quote['bio-link']}")
    soup = BeautifulSoup(res.text, "html.parser")
    birth_date = soup.find(class_="author-born-date").get_text()
    birth_location = soup.find(class_="author-born-location").get_text()
    print(f"Here's a hint: Author was born on {birth_date}{birth_location}")

  elif remaining_guesses == 2:
    print(f"Here's another hint: Author first name is {quote['author'][0]}")

  elif remaining_guesses == 1:
    last_name = quote['author'].split(" ")[1][0]
    print(f"Here's another hint: Author last name is {last_name}")

  else:
    print(f"Sorry you're out of guesses. Author was {quote['author']}")

